# Server configuration
server.port=8080

# Database Configuration (In-Memory H2 DB)
spring.datasource.url=jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console Configuration (for testing and manual database inspection)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Allows using frame tags inside the H2 console layout
spring.headers.frame-options.disable=true 

# JPA/Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
