name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: |
          docker build -t backend-app -f backend/Dockerfile .

      - name: Build frontend Docker image
        run: |
          docker build -t frontend-app -f frontend/Dockerfile .

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image: backend-app
          format: table
          exit-code: 1

      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image: frontend-app
          format: table
          exit-code: 1
